# Generated by Django 5.2.7 on 2025-10-28 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('turno', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Hospedes',
            fields=[
                ('id_hospede', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('idade', models.IntegerField()),
            ],
            options={
                'db_table': 'hospedes',
            },
        ),
        migrations.CreateModel(
            name='Quartos',
            fields=[
                ('num_quarto', models.IntegerField(primary_key=True, serialize=False)),
                ('disponibilidade', models.BooleanField(default=True)),
                ('tipo', models.CharField(max_length=50)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_id_hospede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hospedes')),
            ],
            options={
                'db_table': 'quartos',
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_resrva', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('fk_id_hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospedes')),
                ('fk_num_quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quartos')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id_relatorio', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('conteudo', models.TextField()),
                ('fk_id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.funcionarios')),
                ('fk_id_hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospedes')),
                ('fk_id_quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quartos')),
                ('fk_id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservas')),
            ],
            options={
                'db_table': 'relatorios',
            },
        ),
    ]
